In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [3]:
df = pd.read_csv('breast-cancer-wisconsin.csv')

In [4]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

            ...             radius_worst  texture_worst  perimeter_worst  \
0           ...                    25.38          17.33           184.60   
1           ...                    24.99          23.41           158.80   
2           ...                    23.57          25.53           152.50   
3           ...                    14.91          26.50            98.87   
4           ...                    22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 32 columns]

In [5]:
df.shape

(569, 32)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
id                         569 non-null int64
diagnosis                  569 non-null object
radius_mean                569 non-null float64
texture_mean               569 non-null float64
perimeter_mean             569 non-null float64
area_mean                  569 non-null float64
smoothness_mean            569 non-null float64
compactness_mean           569 non-null float64
concavity_mean             569 non-null float64
concave points_mean        569 non-null float64
symmetry_mean              569 non-null float64
fractal_dimension_mean     569 non-null float64
radius_se                  569 non-null float64
texture_se                 569 non-null float64
perimeter_se               569 non-null float64
area_se                    569 non-null float64
smoothness_se              569 non-null float64
compactness_se             569 non-null float64
concavity_se               569 non

In [7]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean           ...             radius_worst  texture_worst  \
count     569.000000           ...               569.000000     569.000000   
mean        0.181162           ...                16.269190      25.677223   
std         0.027414           ...                 4.833242       6.146258   
min         0.106000           ...                 7.930000      12.020000   
25%         0.161900           ...                13.010000      21.080000   
50%         0.179200           ...                14.970000      25.410000   
75%         0.195700           ...                18.790000      29.720000   
max         0.304000           ...                36.040000      49.540000   

       perimeter_worst   area_worst  smoothness_worst  compactness_worst  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       concavity_worst  concave points_worst  symmetry_worst  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       fractal_dimension_worst  
count               569.000000  
mean                  0.083946  
std                   0.018061  
min                   0.055040  
25%                   0.071460  
50%                   0.080040  
75%                   0.092080  
max                   0.207500  

[8 rows x 31 columns]

In [8]:
df[df['diagnosis']=='M']['id'].count()

212

In [9]:
df[df['diagnosis']=='B']['id'].count()

357

In [10]:
y=df.iloc[:,[1]]

In [11]:
y=pd.DataFrame(np.where(y['diagnosis']=='M',1,0), columns=['diagnosis'])

In [12]:
X=df.iloc[:,1:12].drop(columns=['diagnosis'])

In [13]:
X.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  
0                 0.07871  
1                 0.05667  
2                 0.05999  
3                 0.09744  
4                 0.05883

<h2>Data Pre-processing</h2>

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0)

In [16]:
sc_X=StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

<h2>Model Fitting</h2>

<h3>Logistic Regression</h3>

In [17]:
from sklearn.feature_selection import f_classif
p_val = f_classif(X_train,y_train)[1]
p_val

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2.55823842e-69, 8.37108067e-18, 8.19690935e-73, 1.48052645e-62,
       1.27734112e-15, 9.49913611e-45, 1.45377554e-60, 8.98762428e-87,
       3.44436651e-13, 6.30247708e-01])

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
mean_logit_classifier = LogisticRegression(random_state=0)
mean_logit_classifier.fit(X_train, y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
#Logit co-efficients
predictors = X.columns
coeffs = mean_logit_classifier.coef_[0]

In [35]:
predictor_coefficients_logit = pd.DataFrame(columns=['predictor','co-efficient'])
for i in range(len(predictors)):
    predictor_coefficients_logit.loc[i]=[predictors[i], coeffs[i]]
    
predictor_coefficients_logit

predictor  co-efficient
0             radius_mean      1.010016
1            texture_mean      1.344157
2          perimeter_mean      0.933628
3               area_mean      1.178509
4         smoothness_mean      1.020748
5        compactness_mean     -0.021437
6          concavity_mean      0.775319
7     concave points_mean      1.464834
8           symmetry_mean      0.569714
9  fractal_dimension_mean     -0.482281

<h2>Prediction and model performance</h2>

In [52]:
y_pred_logit = mean_logit_classifier.predict(X_test)

In [53]:
y_pred_logit[0:20]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1])

In [24]:
y_pred_prob = mean_logit_classifier.predict_proba(X_test)[:,1]

In [25]:
y_pred_prob[0:20]

array([8.70663573e-01, 1.50668821e-01, 8.87958890e-03, 6.35920359e-03,
       1.51728565e-02, 2.76162846e-02, 3.92385943e-03, 6.02292943e-03,
       3.30327592e-04, 5.42583994e-04, 3.63808472e-01, 3.78907969e-01,
       2.22897446e-04, 4.13229871e-01, 7.58758773e-01, 9.68175637e-01,
       1.67628654e-02, 9.99897673e-01, 9.99910813e-01, 9.99998108e-01])

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score

In [27]:
cm_logit_mean = confusion_matrix(y_test, y_pred)

In [28]:
cm_logit_mean

array([[86,  4],
       [ 5, 48]], dtype=int64)

In [29]:
accuracy_score_logit_mean = accuracy_score(y_test, y_pred)
accuracy_score_logit_mean

0.9370629370629371

In [30]:
##Calculating the null accuracy
null_accuracy_score = y_test[y_test['diagnosis']==0]['diagnosis'].count()/y_test['diagnosis'].count()
null_accuracy_score

0.6293706293706294

In [50]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import cross_val_score
accuracies_logit_mean = cross_val_score(estimator=mean_logit_classifier, X=X_train, y=y_train, cv=10)
print('Accuracies of training folds are :'+str(accuracies_logit_mean))
print('Mean accuracy after cross validation :' +str(accuracies_logit_mean.mean()))

Accuracies of training folds are :[0.90697674 0.97674419 0.93023256 0.90697674 0.88372093 0.93023256
 0.93023256 0.92857143 0.97619048 0.95121951]
Mean accuracy after cross validation :0.9321097696026793


<h3>SVM</h3>

<h4>Support Vector Classifier with Linear Kernel</h4>

In [55]:
from sklearn.svm import SVC
mean_svm_linear_classifier = SVC(kernel='linear', random_state=0)
mean_svm_linear_classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [56]:
y_pred_svm_linear = mean_svm_linear_classifier.predict(X_test)

In [57]:
cm_svm_linear_mean = confusion_matrix(y_test, y_pred)

In [58]:
cm_svm_linear_mean

array([[85,  5],
       [ 5, 48]], dtype=int64)

In [61]:
accuracy_score_svm_linear_mean = accuracy_score(y_test, y_pred_svm_linear)
accuracy_score_svm_linear_mean

0.9300699300699301

In [60]:
import warnings
warnings.filterwarnings('ignore')

accuracies_svm_linear_mean = cross_val_score(estimator=mean_svm_linear_classifier, X=X_train, y=y_train, cv=10)
print('Accuracies of training folds are :'+str(accuracies_svm_linear_mean))
print('Mean accuracy after cross validation :' +str(accuracies_svm_linear_mean.mean()))

Accuracies of training folds are :[0.90697674 0.95348837 0.95348837 0.93023256 0.88372093 0.93023256
 0.93023256 0.92857143 0.97619048 0.92682927]
Mean accuracy after cross validation :0.9319963266077844


<h4>Support Vector Classifier with Radial (Gaussian) Kernel</h4>

In [62]:
mean_svm_radial_classifier = SVC(kernel='rbf', random_state=0)
mean_svm_radial_classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [63]:
y_pred_svm_radial = mean_svm_radial_classifier.predict(X_test)

In [64]:
cm_svm_radial_mean = confusion_matrix(y_test, y_pred_svm_radial)

In [65]:
cm_svm_radial_mean

array([[88,  2],
       [ 5, 48]], dtype=int64)

In [67]:
accuracy_score_svm_radial_mean = accuracy_score(y_test, y_pred_svm_radial)
accuracy_score_svm_radial_mean

0.951048951048951

In [68]:
import warnings
warnings.filterwarnings('ignore')

accuracies_svm_radial_mean = cross_val_score(estimator=mean_svm_radial_classifier, X=X_train, y=y_train, cv=10)
print('Accuracies of training folds are :'+str(accuracies_svm_radial_mean))
print('Mean accuracy after cross validation :' +str(accuracies_svm_radial_mean.mean()))

Accuracies of training folds are :[0.90697674 0.93023256 0.97674419 0.93023256 0.90697674 0.95348837
 0.93023256 0.95238095 1.         0.95121951]
Mean accuracy after cross validation :0.9438484185506306
